SELECT C.AUTHOR_ID, D.AUTHOR_NAME, C.CATEGORY, SUM(C.TOTAL_SALES)
FROM
(
    SELECT AUTHOR_ID, CATEGORY, B.TOTAL*A.PRICE AS TOTAL_SALES
    FROM BOOK A
    LEFT JOIN
    (
        SELECT SUM(SALES) AS TOTAL, BOOK_ID
        FROM BOOK_SALES
        WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
        GROUP BY BOOK_ID
    ) B
    ON A.BOOK_ID=B.BOOK_ID
) C
LEFT JOIN 
(
    SELECT *
    FROM AUTHOR
) D
ON C.AUTHOR_ID=D.AUTHOR_ID
GROUP BY C.AUTHOR_ID, C.CATEGORY
ORDER BY C.AUTHOR_ID, C.CATEGORY DESC