SELECT A.ITEM_ID, A.ITEM_NAME, A.RARITY
FROM ITEM_INFO A
JOIN
(
    SELECT *
    FROM ITEM_TREE B
    WHERE NOT EXISTS
    (
        SELECT PARENT_ITEM_ID
        FROM ITEM_TREE C
        WHERE B.ITEM_ID = C.PARENT_ITEM_ID
    )
) B
ON A.ITEM_ID = B.ITEM_ID
ORDER BY A.ITEM_ID DESC