SELECT
    A.CAR_ID,
    A.CAR_TYPE,
    TRUNCATE(A.DAILY_FEE * 30 * (100 - P.DISCOUNT_RATE) / 100, 0) AS FEE
FROM
    CAR_RENTAL_COMPANY_CAR A
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
    ON A.CAR_TYPE = P.CAR_TYPE
WHERE
    A.CAR_TYPE IN ('세단', 'SUV')
    AND P.DURATION_TYPE = '30일 이상'
    AND A.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
    )
    AND A.DAILY_FEE * 30 * (100 - P.DISCOUNT_RATE) / 100 BETWEEN 500000 AND 1999999
ORDER BY
    FEE DESC,
    A.CAR_TYPE ASC,
    A.CAR_ID DESC;
