SELECT YEAR(B.SALES_DATE) AS YEAR, MONTH(B.SALES_DATE) AS MONTH, A.GENDER, COUNT(DISTINCT A.USER_ID) AS USERS
FROM ONLINE_SALE B
JOIN USER_INFO A
ON B.USER_ID = A.USER_ID
GROUP BY YEAR(B.SALES_DATE), MONTH(B.SALES_DATE), A.GENDER
HAVING A.GENDER IS NOT NULL
ORDER BY YEAR(B.SALES_DATE), MONTH(B.SALES_DATE), A.GENDER

# SELECT *
# FROM ONLINE_SALE
# WHERE USER_ID != 2

# SELECT *
# FROM USER_INFO
# WHERE GENDER IS NULL

# SELECT YEAR(B.SALES_DATE) AS YEAR, MONTH(B.SALES_DATE) AS MONTH, A.GENDER, COUNT(*) AS USERS
# FROM ONLINE_SALE B
# JOIN USER_INFO A
# ON B.USER_ID = A.USER_ID
# GROUP BY YEAR(B.SALES_DATE), MONTH(B.SALES_DATE), A.GENDER
# HAVING A.GENDER IS NULL
# ORDER BY YEAR(B.SALES_DATE), MONTH(B.SALES_DATE), A.GENDER