WITH U2021 AS(
    SELECT USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
)

SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, COUNT(DISTINCT(A.USER_ID)) AS PURCHASED_USERS, 
    ROUND(COUNT(DISTINCT(A.USER_ID))/(SELECT COUNT(*)
        FROM U2021), 1) AS PUCHASED_RATIO
FROM ONLINE_SALE A
JOIN U2021 B
ON A.USER_ID = B.USER_ID
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY YEAR(SALES_DATE), MONTH(SALES_DATE)
