SELECT A.CAR_ID,
    CASE WHEN SUM(CASE WHEN B.TMP = '대여중' THEN 1 ELSE 0 END)=0 THEN '대여 가능'
    ELSE '대여중'
    END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
LEFT JOIN(
    SELECT CAR_ID,
        CASE WHEN '2022-10-16' BETWEEN START_DATE AND END_DATE THEN '대여중'
        ELSE '대여 가능'
    END AS TMP
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
) B
ON A.CAR_ID = B.CAR_ID
GROUP BY A.CAR_ID
ORDER BY A.CAR_ID DESC