SELECT A.PRODUCT_ID, B.PRODUCT_NAME, (B.PRICE*A.AMOUNT) AS TOTAL_SALES
FROM
(
    SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT
    FROM FOOD_ORDER
    WHERE PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
    GROUP BY PRODUCT_ID
) A
JOIN FOOD_PRODUCT B
ON A.PRODUCT_ID = B.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID