SELECT D.MEMBER_NAME, C.REVIEW_TEXT, DATE_FORMAT(C.REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW C
INNER JOIN(
    SELECT A.MEMBER_ID, B.MEMBER_NAME, COUNT(*) AS CNT
    FROM REST_REVIEW A
    INNER JOIN MEMBER_PROFILE B
    ON A.MEMBER_ID = B.MEMBER_ID
    GROUP BY A.MEMBER_ID
    ORDER BY CNT DESC
    LIMIT 1) D
ON C.MEMBER_ID = D.MEMBER_ID
ORDER BY REVIEW_DATE, C.REVIEW_DATE