SELECT A.MCDP_CD AS "진료과 코드", COUNT(*) AS "5월예약건수"
FROM APPOINTMENT A JOIN (SELECT APNT_NO, MCDP_CD FROM APPOINTMENT
WHERE APNT_YMD LIKE "2022-05%") B
ON A.APNT_NO = B.APNT_NO
GROUP BY A.MCDP_CD
ORDER BY COUNT(*), A.MCDP_CD