SELECT CATEGORY, COUNT(*) AS PRODUCTS
FROM PRODUCT A LEFT JOIN (
SELECT SUBSTRING(PRODUCT_CODE,1,2) AS CATEGORY, PRODUCT_ID
FROM PRODUCT
    ) AS B
ON A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY CATEGORY
ORDER BY CATEGORY