WITH TMP AS(
    SELECT B.DEPT_ID, ROUND(SUM(A.SAL)/COUNT(A.SAL),0) AS AVG_SAL 
    FROM HR_EMPLOYEES A
    JOIN HR_DEPARTMENT B
    ON A.DEPT_ID = B.DEPT_ID
    GROUP BY B.DEPT_ID)

SELECT A.DEPT_ID, B.DEPT_NAME_EN, A.AVG_SAL
FROM TMP A
JOIN HR_DEPARTMENT B
ON A.DEPT_ID = B.DEPT_ID
ORDER BY A.AVG_SAL DESC