WITH TMP AS(
    SELECT ID, FISH_TYPE, IF(LENGTH<=10,10,LENGTH) AS LENGTH, TIME
    FROM FISH_INFO
)


SELECT COUNT(*) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE
FROM TMP
GROUP BY FISH_TYPE
HAVING SUM(LENGTH)/COUNT(*) >= 33
ORDER BY FISH_TYPE